server:
  port: 3000
  
spring:
  datasource:
    url: jdbc:mysql://database-1.cskxmd3bbixc.us-east-2.rds.amazonaws.com/project?useSSL=false&serverTimezone=UTC
    username: root
    password: pass$1234
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: team.egasseva@gmail.com
    password: Egasseva0
  level: 
    org.springframework: WARN
    org.hibernate: WARN
    com.springsecurity.demo: DEBUG           