spring:
  cloud:
    config:
      uri: http://localhost:8765
  application:    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: pass@word1
  jpa:
    hibernate:      ddl-auto: update
server:  port: 0
