spring:
  application:    name: product-service
  cloud:
    config:
      uri: http://localhost:8765
  h2:
    console:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://mongodbuser:mongodbuser@cluster0-gp4w1.mongodb.net/products?retryWrites=true&w=majority
    
server:
  port: 0
  