spring:  datasource:    url: jdbc:mysql://localhost:3306/project
    username: root
    password: pass@word1  data:    mongodb:      uri: mongodb+srv://mongodbuser:mongodbuser@cluster0-gp4w1.mongodb.net/zipcode?retryWrites=true&w=majority
server:  port: 5000