server:
  port: 0
eureka:
  client:
    server:
      waitTimeInMsWhenSyncEmpty: 0
spring:
  application:
    name: dealer-service
  cloud:
    config:
      uri: http://localhost:8765
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: none
